### ISSUE TITLE
Unused reference to SolverInterface.c

### ISSUE THREAD

**Issue by MakisH** [precice/PreCICE.jl#45]
Looks like this variable can be removed:

https://github.com/precice/PreCICE.jl/blob/752ecec43124b0e6d63920acdf729711a4493f2d/test/Makefile#L5

(I just got confused while searching for SolverInterface here)

**Comment by erikscheurer** [comment]
This line is required for the tests. The bindings can be installed without calling this Makefile. 
The `SolverInterface.c` file in this location is part of the unit tests and serves as a dummy interface to imitate the actual SolverInterface. 

We could rename it to `DummySolverInterface.c`?

**Comment by MakisH** [comment]
Ah, I see why I got confused. Yes, I guess renaming would help to also better reflect the purpose.
