### ISSUE TITLE
Correspondance between PreCICE.jl and source code

### ISSUE THREAD

**Issue by marinlauber** [precice/PreCICE.jl#53]
Hi, 

I am playing around with the Julia binder for PreCICE, and it seems that there is some mismatch between the functions in the preCICE source code and the Julia binder. Is there a correspondence between the different branches that must be used? Like both should use `v2.5.0` etc.?

Cheers, 

Marin

**Comment by IshaanDesai** [comment]
Hi @marinlauber 

There is indeed a correspondence between the PreCICE.jl (the bindings), and the preCICE versions. This is mentioned in the README of the bindings. If you are using preCICE v2.5.0, then please use the bindings [v2.5.0](https://github.com/precice/PreCICE.jl/releases/tag/v2.5.0) to ensure compatibility.

**Comment by IshaanDesai** [comment]
What error do you get? The branches [precice:develop](https://github.com/precice/precice/tree/develop) and [PreCICE.jl:develop](https://github.com/precice/PreCICE.jl/tree/develop) should work.

**Comment by marinlauber** [comment]
Hey @IshaanDesai, sorry for the delay.

I am working using the global mesh access with the `precice:release-v3.0.0` branch and using the corresponding `PreCICE.jl:origin/PreCICE.jl-v3.0.0` branch.

The specific function that errors is `getMeshVerticesAndIDs` where I get 
```
LoadError: could not load symbol "precicec_getMeshVerticesAndIDs":
/apps/precice/3.0.0/lib/libprecice.so: undefined symbol: precicec_getMeshVerticesAndIDs
```

I seems there is a mismatch between the function implemented in `PreCICE.jl` and the one in `preCICE`, as the `libprecice.so` doesn't have this function
```
$ nm -D /apps/precice/3.0.0/lib/libprecice.so | grep precicec_get
00000000003b8f90 T precicec_getDataDimensions
00000000003b9230 T precicec_getMaxTimeStepSize
00000000003b8ea0 T precicec_getMeshDimensions
00000000003ba6e0 T precicec_getMeshVertexIDsAndCoordinates
00000000003b97e0 T precicec_getMeshVertexSize
00000000003ba680 T precicec_getVersionInformation
```

Is that because I am not using the correct branch for the library to correspond?

**Comment by IshaanDesai** [comment]
@marinlauber we have indeed missed updating an old function name to `getMeshVertexIDsAndCoordinates`. We did not catch this in the CI because we have no test which actually calls this function. So thanks for catching this! I will fix this and also the version, and then create another release.
